[package]
name = "sx1276"
version = "0.1.0"
authors = ["Louis Thiery <louis@helium.com>"]
edition = "2018"

[dependencies]
libc =  { version = "0.2", default-features = false }
sx1276-sys = {path = "./sx1276-sys"}
